[package]
name = "opa-rego"
version = "0.1.0"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
edition = "2018"

[lib]
name = "opa_rego"

[dependencies]
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dev-dependencies]
env_logger = "0.6"
